FROM mcr.microsoft.com/playwright:v1.58.2-noble

ARG DATABASE_URL
ARG BETTER_AUTH_SECRET
ARG BETTER_AUTH_URL
ARG RESEND_API_KEY
ARG RESEND_FROM_EMAIL
ARG UPLOADTHING_TOKEN
ARG UPLOADTHING_SECRET
ARG UPLOADTHING_APP_ID
ARG CRON_SECRET
ARG GITHUB_TOKEN
ARG OPENAI_API_KEY
ARG OPENAI_MODEL
ARG NEXT_PUBLIC_APP_NAME

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
ENV DATABASE_URL=$DATABASE_URL
ENV BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
ENV BETTER_AUTH_URL=$BETTER_AUTH_URL
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV RESEND_FROM_EMAIL=$RESEND_FROM_EMAIL
ENV UPLOADTHING_TOKEN=$UPLOADTHING_TOKEN
ENV UPLOADTHING_SECRET=$UPLOADTHING_SECRET
ENV UPLOADTHING_APP_ID=$UPLOADTHING_APP_ID
ENV CRON_SECRET=$CRON_SECRET
ENV GITHUB_TOKEN=$GITHUB_TOKEN
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV OPENAI_MODEL=$OPENAI_MODEL
ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10.28.2 --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm build

EXPOSE 8080

CMD ["sh", "-lc", "pnpm exec next start -H 0.0.0.0 -p ${PORT:-8080}"]
